# -- coding: utf-8 --
{
    'name': "HRMS Employee Training Data",
    'version': '16.0.1.0.0',
    'summary': """Manage training data for the Civil Service""",
    'description': """Manage training data for the Civil Service""",
    'category': 'Generic Modules/Human Resources',
    'author': 'Chisenga Musonda',
    'website': "",
    'depends': [
        'mail',
        'base',
        'hr'
    ],
    'data': [
        'security/training_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        # 'wizard/createTrainingPlanView.xml',
        'views/trainingPlan.xml',
        # 'views/trainingPlanApprovalHRDC.xml',
        # 'views/trainingPlanApprovalPS.xml',
        # 'views/trainingPlanApprovalPSMD.xml',
        # 'views/typeOfTraining.xml',
        # 'views/fieldOfStudy.xml',
        # 'views/levelOfStudy.xml',
        'views/training_views.xml',
        'views/end_of_course_evaluation.xml',
        'views/post_training_evaluation.xml',
        'views/supervisors_post_training_evaluation.xml',
    ],
    'demo': [],
    'images': ["static/description/banner.png"],
    'license': "AGPL-3",
    'installable': True,
    'application': False,
}
